### ISSUE TITLE
Grid Image

### ISSUE THREAD

**Issue by Kristoffer95** [DevTips/Parallax-on-the-Web-DevTips-#33]
**Travis**, 
I've got a problem. On 3:22 in the video( Part 3), the images are not showing on my browser. I am also using skeleton framework. I'm not quite sure if the problem is in my browser(Mozilla 53.0.3 (32-bit))? I just copied the code you provided on the video. How would I fix this?

P.S: The final output of your github code is working. (very confusing) 

Files link: https://www.dropbox.com/sh/89g3qmn977nfk7c/AAABm1rpDofesIoXHzRbH0kca?dl=0

**THANK YOU**!﻿

**Comment by MilesWilliams** [comment]
I downloaded your code and all the images are showing up for me - the one model image wasn't showing because it had an opacity of 0 on it in the css. The reason if i remember was because in the jQuery, on window position there should be a function that adds the opacity when you scroll down but this isn't in your js file thus the image will remain with an opacity of 0

**Comment by Kristoffer95** [comment]
Thank you so much for the reply sir, very well appreciated. I really didn't notice that opacity: 0. That gave me a headache. Ugghh hahaha
